// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verify_email.sql

package db

import (
	"context"
	"database/sql"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :execresult
INSERT INTO verify_emails (
    user_account,
    email, 
    secret_code
) VALUES (?, ?, ?)
`

type CreateVerifyEmailParams struct {
	UserAccount string `json:"user_account"`
	Email       string `json:"email"`
	SecretCode  string `json:"secret_code"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVerifyEmail, arg.UserAccount, arg.Email, arg.SecretCode)
}
