// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rpc_send_passcode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPassCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendPassCodeRequest) Reset() {
	*x = SendPassCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_send_passcode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPassCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPassCodeRequest) ProtoMessage() {}

func (x *SendPassCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_send_passcode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPassCodeRequest.ProtoReflect.Descriptor instead.
func (*SendPassCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_send_passcode_proto_rawDescGZIP(), []int{0}
}

func (x *SendPassCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendPassCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPassCodeResponse) Reset() {
	*x = SendPassCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_send_passcode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPassCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPassCodeResponse) ProtoMessage() {}

func (x *SendPassCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_send_passcode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPassCodeResponse.ProtoReflect.Descriptor instead.
func (*SendPassCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_send_passcode_proto_rawDescGZIP(), []int{1}
}

var File_rpc_send_passcode_proto protoreflect.FileDescriptor

var file_rpc_send_passcode_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2b, 0x0a,
	0x13, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x47, 0x6e, 0x43, 0x2f, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x42, 0x61, 0x6e, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_send_passcode_proto_rawDescOnce sync.Once
	file_rpc_send_passcode_proto_rawDescData = file_rpc_send_passcode_proto_rawDesc
)

func file_rpc_send_passcode_proto_rawDescGZIP() []byte {
	file_rpc_send_passcode_proto_rawDescOnce.Do(func() {
		file_rpc_send_passcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_send_passcode_proto_rawDescData)
	})
	return file_rpc_send_passcode_proto_rawDescData
}

var file_rpc_send_passcode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_send_passcode_proto_goTypes = []any{
	(*SendPassCodeRequest)(nil),  // 0: pb.SendPassCodeRequest
	(*SendPassCodeResponse)(nil), // 1: pb.SendPassCodeResponse
}
var file_rpc_send_passcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_send_passcode_proto_init() }
func file_rpc_send_passcode_proto_init() {
	if File_rpc_send_passcode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_send_passcode_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SendPassCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_send_passcode_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SendPassCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_send_passcode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_send_passcode_proto_goTypes,
		DependencyIndexes: file_rpc_send_passcode_proto_depIdxs,
		MessageInfos:      file_rpc_send_passcode_proto_msgTypes,
	}.Build()
	File_rpc_send_passcode_proto = out.File
	file_rpc_send_passcode_proto_rawDesc = nil
	file_rpc_send_passcode_proto_goTypes = nil
	file_rpc_send_passcode_proto_depIdxs = nil
}
